name: "Check for vulnerabilities in docker image"

on:
  pull_request:
    branches: [ main ]

permissions:
  id-token: write
  actions: read
  contents: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner against alpine:3.4
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'alpine:3.4'
          scan-type: 'config'
          hide-progress: false
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
          format: 'sarif'
          output: 'image-scan-trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'image-scan-trivy-results.sarif'